### ISSUE TITLE
MESH 怎样 设置 ble 广播间隔?

### ISSUE THREAD

**Issue by mikewen** [Jieli-Tech/fw-AC63_BT_SDK#100]
MESH 下, 功耗很高, 接近 15 mA, 是不是 MESH 不支持 sleep ?

**Comment by NoCodeNoLife-404** [comment]
mesh的广播间隔在mesh_config_common.c里设置，scan的windows和interval在sacn_core.c里设置。要sleep需要在板级配置里配置这个宏#define TCFG_LOWPOWER_LOWPOWER_SEL    SLEEP_EN。
