### ISSUE TITLE
关于IOS的OTA Update 的使用

### ISSUE THREAD

**Issue by maxbang5** [Jieli-Tech/fw-AC63_BT_SDK#101]
机器打开了OTA功能，生成的UFW文件怎么放到苹果手机的APP中，安卓是放到对应的文件夹，那IOS呢，微信分享文件并不能发到OTA Update这个软件上，软件也没有粘贴文件的选项，这个找不到对应的使用手册，只有开发手册，麻烦帮忙看下文件怎么放到IOS 的APP中进行升级。

**Comment by maxbang5** [comment]
这个IOS的APP是用不了么

**Comment by main010** [comment]
使用爱思助手或者itune，爱思助手找到对应APP，点击浏览即可将文件导入

**Comment by iCodeHP** [comment]
@maxbang5 用Xcode工程把APP跑起来，使用手机工具入iTunes，爱思助手，iPhone插线连接电脑，然后将ufw文件拖至APP的沙盒里面，在运行APP便可操作。
