### ISSUE TITLE
蓝牙: 温度跟随

### ISSUE THREAD

**Issue by mikewen** [Jieli-Tech/fw-AC63_BT_SDK#102]
SDK 里有: AD_CH_DTEMP

是不是用来读芯片温度的?  返回值怎样换算成温度呢?

**Comment by rixin-Tech** [comment]
可以定性的检测温度变化量，没校准不能转换到实际温度。

**Comment by mikewen** [comment]
虽然没校准，但用来做过温保护应该可以吧？

怎样用返回值估算温度呢?

**Comment by rixin-Tech** [comment]
t1 = adc_get_voltage(AD_CH_DTEMP);
温度变化10度，电压变化30mv。
