### ISSUE TITLE
SPP_LE 工程编译 问题

### ISSUE THREAD

**Issue by mikewen** [Jieli-Tech/fw-AC63_BT_SDK#105]
再 app_config.h 该为蓝牙(ble主机)透传
#define TRANS_DATA_EN                     0 //蓝牙双模透传
#define TRANS_CLIENT_EN                   1 //蓝牙(ble主机)透传

编译报错:
le_client_demo.c | 1111 | error: use of undeclared identifier 'cur_dev_cid'|

再 app_config.h 该为 蓝牙BLE ibeacon
#define TRANS_DATA_EN                     0 //蓝牙双模透传
#define TRANS_CLIENT_EN                   0 //蓝牙(ble主机)透传
#define BEACON_MODE_EN                    1 //蓝牙BLE ibeacon

编译报错:
testbox_update.c|140|undefined reference to `ble_app_disconnect'|

SDK version 1.0.0

**Comment by jamin3702** [comment]
1、可以把 cur_dev_cid 去掉，不用传参
2、把接口ble_apps_disconnect 替换为ble_module_enable(0)
3、BEACON_MODE_EN 放在CONFIG_APP_SPP_LE运行，移植到其他模块，要解决编译问题。
