### ISSUE TITLE
AC632N ibeacon和le功能咨询

### ISSUE THREAD

**Issue by alittleray** [Jieli-Tech/fw-AC63_BT_SDK#110]
你好，目前在使用AC632N开发产品，功能需求是这样的：
1、设备(AC692N)开启ibeacon广播，手机app被唤醒后，检测设备和手机之间的距离；
2、当距离小于某个数值时，手机去连接设备；
所以需要设备在ibeacon和自定义ble广播之间定时切换，这个操作是不是可以这样：
1、设备发ibeacon广播包n秒；
2、停止广播，设置广播包为自定义可连接的ble广播，持续广播n秒；
如此反复循环，每次改变广播包内容，先停止广播->设置广播包内容->开始广播，这个流程是否可行，谢谢，祝愉快

**Comment by jamin3702** [comment]
可以这样来实现
