### ISSUE TITLE
这些日志是哪里打印的

### ISSUE THREAD

**Issue by alittleray** [Jieli-Tech/fw-AC63_BT_SDK#127]
芯片:AC6329C
持续打印一堆日志，走的不是log_info函数，请问是哪里打印的，日志表示什么意思，日志如下：
PP
w[]
w[]IP
P
w[]
w[]*I

在打印以下日志后会重启：
PP
I
PP
I
PP
I
PP
I

**Comment by alittleray** [comment]
sdk版本2.0.0

**Comment by main010** [comment]
库里打印的，putchar，打开可发现可连接的时候会打印
