### ISSUE TITLE
如何得到一个精确的us级定时器中断

### ISSUE THREAD

**Issue by alittleray** [Jieli-Tech/fw-AC63_BT_SDK#130]
### 描述：用定时做一个us级别的中断，用来做波形检测。使用定时器3，优先级3，使用24m时钟，4分频；定时器中断中翻转gpio输出方波。
定时周期为100us时，得到一个5K的漂亮方波；定时周期为50us时，得到的方波周期有些100us，有些140us。请问当前芯片是否可以实现50us级别精确的定时器中断

**Comment by wjjjb123** [comment]
中断函数定义到RAM里，中断优先级设最高，系统时钟尽量设高。
由于cpu在执行某些代码指令时，不会立马响应，即延迟响应。
不建议 系统 有us级中断，复杂的环境可能跑不过来

**Comment by wjjjb123** [comment]
中断函数定义到RAM里，中断优先级设最高，系统时钟尽量设高。
由于cpu在执行某些代码指令时，不会立马响应，即延迟响应。
不建议 系统 有us级中断，复杂的环境可能跑不过来

**Comment by alittleray** [comment]
已明了
