### ISSUE TITLE
BLE广播控制问题

### ISSUE THREAD

**Issue by Orang-Lab** [Jieli-Tech/fw-AC63_BT_SDK#137]
![3adad1b9810b73c9755f48906257a1f](https://user-images.githubusercontent.com/95346482/144212413-00c7d0b1-c06e-4c3b-a705-13a0bb56d6bf.png) 1.广播控制无效 是否可以取消，
2.使用杰理SDK自带双备份OTA升级，当升级到一定进度时，突然关闭手机系统的蓝牙，会导致死机。

**Comment by jamin3702** [comment]
1、可以移动一下位置，先关闭广播，在关闭控制。
2、提供一下设备的打印log

**Comment by Orang-Lab** [comment]
收到&nbsp; 谢谢杰理科技的技术支持



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月11日(星期二) 上午8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Jieli-Tech/fw-AC63_BT_SDK] BLE广播控制问题 (Issue #137)





 
1、可以移动一下位置，先关闭广播，在关闭控制。
 2、提供一下设备的打印log
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
