### ISSUE TITLE
BLE定向广播显示线程错误

### ISSUE THREAD

**Issue by Orang-Lab** [Jieli-Tech/fw-AC63_BT_SDK#143]
1.在广播参数里设置ADV_DIRECT_IND定向广播；

![image](https://user-images.githubusercontent.com/95346482/148865130-c6eefe68-9ab3-4f60-a55d-4551ed906638.png)
2.HCI事件 定向广播超时事件
![image](https://user-images.githubusercontent.com/95346482/148865228-2ee5e3ca-c749-4ad1-8c65-8749377e6871.png)
3.log的结果显示 线程报错 导致后续无蓝牙广播
![image](https://user-images.githubusercontent.com/95346482/148865454-fc1868c2-1121-4d45-95d3-5b52d1a4eac6.png)
4.察看了le_gatt_server.c文件，发现里面的处理机制是先产生事件通知再去设置工作状态，如果事件通知给应用层，应用层也设置新的工作状态，会导致设置不生效。

**Comment by jamin3702** [comment]
确实存在上述现象，应该先更新工作状态，再通知应用，多谢指出！

**Comment by jamin3702** [comment]
把顺序换一下，试试

**Comment by Orang-Lab** [comment]
已换了&nbsp; 不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月11日(星期二) 上午9:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Jieli-Tech/fw-AC63_BT_SDK] BLE定向广播显示线程错误 (Issue #143)





 
把顺序换一下，试试
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Orang-Lab** [comment]
显示error了  麻烦帮忙看下是哪里导致的底层错误，然后才是状态设置的先后问题

**Comment by Orang-Lab** [comment]
显示error了&nbsp; 麻烦帮忙看下是哪里导致的底层错误，然后才是状态设置的先后问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jieli-Tech/fw-AC63_BT_SDK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 上午9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jieli-Tech/fw-AC63_BT_SDK] BLE定向广播显示线程错误 (Issue #143)





 
把顺序换一下，试试
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jamin3702** [comment]
上传打印log 和 你的修改看看

**Comment by Orang-Lab** [comment]
[00:00:09.606][Info]: [GATT_SERVER]__gatt_server_just_new_dev_adv

[00:00:09.607][Info]: [GATT_SERVER]new_dev_adv

[00:00:09.607][Info]: [GATT_SERVER]adv_en:1

[00:00:09.608][Info]: [GATT_SERVER]server_work_st:1->20

[00:00:09.609][MUL-PER]server_state: handle=00,20
 
[00:00:09.610][MUL-PER]ble_state:ff===>20
 
[00:00:09.612]init rf_osc:0 PLL_comp:0 
[00:00:09.631][Info]: [USER_MULTI]open --------------------->
[00:00:10.897][Debug]: [LL_E]HCI_SUBEVENT_LE_CONNECTION_COMPLETE 3c

[00:00:10.898](error): <Error>: [LL_ADV]TO - LL Adv High Duty Timeout

[00:00:10.899][Info]: [GATT_SERVER]DIRECT_ADV TO!

[00:00:10.900][MUL-PER]------------------------------------->>>>>>>>>>DIRECT_ADV_TIMEOUT:2 
[00:00:10.902][Info]: [GATT_SERVER]server_work_st:20->2

[00:00:10.904][MUL-PER]server_state: handle=00,02
 
[00:00:10.905][MUL-PER]ble_state:20===>02

**Comment by Orang-Lab** [comment]
![image](https://user-images.githubusercontent.com/95346482/148870009-1fedc8f5-7c34-426e-bceb-239667f15967.png)

**Comment by jamin3702** [comment]
截图没看到调整这个接口  ble_gatt_server_set_adv_config(&hogp_server_adv_config);

**Comment by Orang-Lab** [comment]
![image](https://user-images.githubusercontent.com/95346482/148872025-59eb861b-b3f8-41c7-9ed2-94b0986cef2f.png)
mo'r默认是大家都懂了

**Comment by Orang-Lab** [comment]
这样设置后  开广播使能就会出现log   error

**Comment by jamin3702** [comment]
![image](https://user-images.githubusercontent.com/67721610/148872399-a7f6f464-3e41-448e-885f-3405de14c880.png)
关闭这个，需要调接口开广播

**Comment by Orang-Lab** [comment]
是的  这个了解  但是不是产生错误的原因吧  我是想协助解决为什么底层报错  不是纠结广播与否问题

**Comment by Orang-Lab** [comment]
打开自动广播是会开了广播      但还是会报错 不是我想要了解的问题   如果说这个报错是底层本身存在 我就不纠结了
![image](https://user-images.githubusercontent.com/95346482/148874796-314eadcb-c4f1-4dc8-afaa-23d62ef7adca.png)

**Comment by jamin3702** [comment]
这个不是底层错误，官方协议定义广播类型。高频率的定向广播只能维持1.28秒；未被连接，时间到后结束广播；spec上有描述

**Comment by Orang-Lab** [comment]
但是有看到error
