### ISSUE TITLE
AC6321A sdk200  主从一体工程   开SMP导致连接异常

### ISSUE THREAD

**Issue by Orang-Lab** [Jieli-Tech/fw-AC63_BT_SDK#147]
1.AC6321A sdk200  主从一体工程   开SMP导致AC6321A连接其他从机异常。
2.AC6321开主从一体工程，4主1从，芯片做主机连接其他从机，在没有打开SMP宏CONFIG_BT_SM_SUPPORT_ENABLE时，连接正常；
  当打开CONFIG_BT_SM_SUPPORT_ENABLE宏后，出现底层报[00:00:02.022][Info]: [GATT_CLIENT]start search_profile_all:0050开始进行profile搜索后会出现断开的线程错误，连续几次后才能成功读取从机的profile.如果芯片是全擦除后再下载程序，从机也是一个新的设备，开了SMP宏，这个现象是必现的。希望杰理的技术人员帮忙协助解决一下。谢谢杰理科技的帮助与支持。

![JIELIAC6321A](https://user-images.githubusercontent.com/95346482/156571957-2f43ecc7-34e9-4c3d-a7a0-065650a97cf4.png)

**Comment by jamin3702** [comment]
替换更新这两个库文件试试

**Comment by jamin3702** [comment]
libs

**Comment by jamin3702** [comment]
[bluetooth.zip](https://github.com/Jieli-Tech/fw-AC63_BT_SDK/files/8221025/bluetooth.zip)

**Comment by jamin3702** [comment]
替换更新这两个库文件试试，反馈测试结果
