### ISSUE TITLE
@flash写前一定要擦除吗？

### ISSUE THREAD

**Issue by Williamzhangtw** [Jieli-Tech/fw-AC63_BT_SDK#150]
一擦除就是4K. 我只想写4K的其中一些，我又没有足够的RAM提前把这4K的flash数据保存起来。 这该如何做？

**Comment by jamin3702** [comment]
使用SDK的VM 写入接口，把保存的的数据分类成不同的VM id来管理数据更新。通过vm id 来更新对应的数据部分。
