### ISSUE TITLE
如何配置才能保持VM数据不被擦除

### ISSUE THREAD

**Issue by alittleray** [Jieli-Tech/fw-AC63_BT_SDK#154]
芯片:AC6329C
SDK:2.0.0
描述：开发过程中使用强制下载工具，
[Uploading tools.zip…]()
发现如果修改了board_ac6329c_demo_cfg.h文件，下载程序VM会被擦除。请问该如何解决

**Comment by jamin3702** [comment]
在download.bat 把关键字 -format all 或者 -format vm
