### ISSUE TITLE
低功耗1 和 低功耗2 

### ISSUE THREAD

**Issue by mikewen** [Jieli-Tech/fw-AC63_BT_SDK#157]
低功耗流程 说有 低功耗1 和 低功耗2  两种模式.
https://gitee.com/jieli-tech_fae/IOT-AC630N/blob/master/doc/software/%E9%A9%B1%E5%8A%A8/%E4%BD%8E%E5%8A%9F%E8%80%97%E6%B5%81%E7%A8%8B.md

SDK缺省是不是只进入 低功耗2 ？
什么时候会进入 低功耗1 模式呢? 可以避免进入低功耗1吗?  因为想保持 GPIO控制外围电路

**Comment by jamin3702** [comment]
想保护io可以参考按键的io怎么保护的，添加相应的代码
![image](https://user-images.githubusercontent.com/67721610/168229224-f8c0bd53-18b1-4a39-bb80-7abc1d014b07.png)
