### ISSUE TITLE
Update timer_pwm_init  for BR25 系列芯片

### ISSUE THREAD

**Issue by mikewen** [Jieli-Tech/fw-AC63_BT_SDK#158]
我想尝试自己更新 timer_pwm_init 
FO_TMR0_PWM FO_TMR1_PWM FO_TMR2_PWM FO_TMR3_PWM 
在 BR25 里没有定义, 应该是什么值？

BR25 支持 gpio_set_fun_output_port  吗?

**Comment by rixin-Tech** [comment]
不支持
