### ISSUE TITLE
连接断开后异常日志

### ISSUE THREAD

**Issue by alittleray** [Jieli-Tech/fw-AC63_BT_SDK#168]
芯片:AC6329C
SDK版本:2.0
描述：手机App通过ble与设备建立建立，设备有Indicate属性的特性，App连接上之后会打开Indicate。当手机与设备连接断开之后，设备会一直打印一下日志：
[00:16:16.893][Info]: [GATT_SERVER]ATT_EVENT_HANDLE_VALUE_INDICATION_COMPLETE:conn_handle= 0000,att_handle= 0000

请问，这个日志是什么意思，我需要做什么操作呢，谢谢

**Comment by JL-MinXian** [comment]
有给手机发indicate包吗？最好提供完整的log信息

**Comment by alittleray** [comment]
> 有给手机发indicate包吗？最好提供完整的log信息

有给手机发indicate包，手机和设备断开连接之后，设备sdk就会间隔打印上面这条日志

**Comment by alittleray** [comment]
今天发现没有打印，我查找一下自己程序，非常感谢
