### ISSUE TITLE
如何获取对端RSSI

### ISSUE THREAD

**Issue by alittleray** [Jieli-Tech/fw-AC63_BT_SDK#172]
芯片：AC6329C
SDK版本：2.0
实例：spp_and_le
描述：手机跟设备连接之后，设备端需要定时获取手机端的RSSI，没发现有现成的API去获取RSSI，怎么样获取比较好

**Comment by JL-MinXian** [comment]
详见说明 https://gitee.com/Jieli-Tech/fw-AC63_BT_SDK/issues/I5IQ1I

**Comment by alittleray** [comment]
已解决，感谢
