### ISSUE TITLE
关于Indicate特性使用

### ISSUE THREAD

**Issue by alittleray** [Jieli-Tech/fw-AC63_BT_SDK#173]
芯片: AC6329C
SDK: 2.0
实例: spp_and_le
描述：设备与手机App通过BLE通信，设备为Server。设备提供一个Write和一个Indicate特性，手机通过设备的Write特性向设备发送数据，设备通过Indicate属性向手机发数据。

当设备通过Indicate属性发送数据后，我看到sdk日志里面有一条日志，如下：
[GATT_SERVER]ATT_EVENT_HANDLE_VALUE_INDICATION_COMPLETE:conn_handle= 0050,att_handle= 000a

请问打印这条日志的时候，设备端是已经收到手机的Ack了吗；我是否可以在收到这条日志后，继续发送剩余的数据。谢谢

**Comment by JL-MinXian** [comment]
该消息表示已经收到对方的ACK行为，可以继续向对方发数据

**Comment by alittleray** [comment]
好的，多谢
