### ISSUE TITLE
列出的硬件IIC端口和芯片规格书不一致？

### ISSUE THREAD

**Issue by HleChen** [Jieli-Tech/fw-AC63_BT_SDK#175]
在fw-AC63_BT_SDK/apps/spp_and_le/board/bd19/board_ac632n_demo_cfg.h 文件里，
列出了四组可选的IIC端口：
IIC配置  /*硬件IIC端口选择
  	SCL         SDA
  'A': IO_PORT_DP   IO_PORT_DM
  'B': IO_PORTA_09  IO_PORTA_10
  'C': IO_PORTA_07  IO_PORTA_08
  'D': IO_PORTA_05  IO_PORTA_06
 */
根据数据手册，'B'应该为USB1DP和USB1DM， 'D'应该为IO_PORTA_03  IO_PORTA_04。
此处是否有误？

**Comment by JL-MinXian** [comment]
https://gitee.com/Jieli-Tech/fw-AC63_BT_SDK/issues/I5N0SR
