### ISSUE TITLE
Ble已经断开但是还持续上报ATT_EVENT_HANDLE_VALUE_INDICATION_COMPLETE

### ISSUE THREAD

**Issue by alittleray** [Jieli-Tech/fw-AC63_BT_SDK#178]
芯片：AC6329C
SDK：2.0
问题描述：手机App与设备通过Ble连接，设备提供一个Write特性用于手机向设备发送数据，同时设备提供一个Indicate特性用于向手机App发送数据。双方通信良好，此时直接关闭手机蓝牙(或者拿着手机远离导致断开)，会持续出现一下日志：
IPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPP
[00:01:10.210][Info]: [GATT_SERVER]ATT_EVENT_HANDLE_VALUE_INDICATION_COMPLETE:conn_handle= 0000,att_handle= 0000

[+XLOG:[0 0:1:10.230][e][xpfles]receive indicate complete but now in indicate step, step=0x20
IPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPP
[00:01:40.210][Info]: [GATT_SERVER]ATT_EVENT_HANDLE_VALUE_INDICATION_COMPLETE:conn_handle= 0000,att_handle= 0000

[+XLOG:[0 0:1:40.230][e][xpfles]receive indicate complete but now in indicate step, step=0x20
IPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIP
[00:02:10.210][Info]: [GATT_SERVER]ATT_EVENT_HANDLE_VALUE_INDICATION_COMPLETE:conn_handle= 0000,att_handle= 0000

P[+XLOG:[0 0:2:10.230][e][xpfles]receive indicate complete but now in indicate step, step=0x20
IPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPPIPPIPPIPP
[00:02:40.210][Info]: [GATT_SERVER]ATT_EVENT_HANDLE_VALUE_INDICATION_COMPLETE:conn_handle= 0000,att_handle= 0000

I[+XLOG:[0 0:2:40.230][e][xpfles]receive indicate complete but now inP indicate step, step=0x20
PIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPP
[00:03:10.210][Info]: [GATT_SERVER]ATT_EVENT_HANDLE_VALUE_INDICATION_COMPLETE:conn_handle= 0000,att_handle= 0000

[+XLOG:[0 0:3:10.230][e][xpfles]receive indicate complete but now in indicate step, step=0x20
IPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPPIPP

**Comment by JL-MinXian** [comment]
需要更新库来测测
[btstack.zip](https://github.com/Jieli-Tech/fw-AC63_BT_SDK/files/9487366/btstack.zip)
