### ISSUE TITLE
设备向手机端发起绑定请求

### ISSUE THREAD

**Issue by alittleray** [Jieli-Tech/fw-AC63_BT_SDK#182]
SDK版本： 2.1.0
芯片型号： AC6329C
选用的cbp工程： AC632N_hid
配置的板级: CONFIG_BOARD_AC6329C_DEMO
问题的分类标签： 蓝牙（BLE&EDR）
问题具体描述： 手机App连接设备，向设备发送命令使设备向当前连接他的手机发起绑定请求。我看到在文件ble_hogp.c中有一个函数 void ble_set_pair_list_control(u8 mode)，像这样 ble_set_pair_list_control(2) 调用该函数，日志如下：
[00:21:46.934][BLE_HOGP]ble_set_pair_list_control: 02,ret=01
但是手机没有任何反应，是我对这个函数理解有误或者对蓝牙绑定理解错误吗，怎么样才能让设备主动去绑定当前连接的手机，并且在手机已配对设备中有这个设备。谢谢。

**Comment by JL-MinXian** [comment]
参考回复：https://gitee.com/Jieli-Tech/fw-AC63_BT_SDK/issues/I5T8FA
