### ISSUE TITLE
[功耗问题]AC6366C_DEMO_V1.0开发板样例测试，峰值电流高于25mA

### ISSUE THREAD

**Issue by angxiaoyang** [Jieli-Tech/fw-AC63_BT_SDK#22]
![image](https://user-images.githubusercontent.com/65414837/99630158-55dc3580-2a74-11eb-867d-66b2f5596f96.png)

1. 原厂测试功耗范围是多少
2. 怎么降低功耗

**Comment by Tsai1005** [comment]
Q1:LDO 模式下Radio 功耗Tx 瞬态会达到35mA~45mA

Q2:降低发射功率，减少Payload，增加通讯间隔

**Comment by angxiaoyang** [comment]
Q1：如何降低发射功率？
Q2：发射功率的范围可调节为多少？

**Comment by angxiaoyang** [comment]
> Q1:LDO 模式下Radio 功耗Tx 瞬态会达到35mA~45mA
> 
> Q2:降低发射功率，减少Payload，增加通讯间隔

Q3：如何降低发射功率？
Q4：发射功率的范围可调节为多少？

**Comment by Tsai1005** [comment]
Q3: 可以通过配置工具，或者程序 调用设置

```
void bt_max_pwr_set(u8 pwr, u8 pg_pwr, u8 iq_pwr, u8 ble_pwr)

````
Q4:-50dB ~ 5dB
