### ISSUE TITLE
串口升级

### ISSUE THREAD

**Issue by stronges** [Jieli-Tech/fw-AC63_BT_SDK#26]
通过 串口接受升级包，然后芯片升级， 这个方案可行么？难度怎么样？可以提供升级流程及相关资料么？AC6368A

**Comment by yzb201611** [comment]
636x可以通过串口升级，这个sdk暂时没提供相关接口及协议，后续可以开放。如果采用单备份升级需要用我们协议来做，若是双备份升级，则可以自定义协议格式。

**Comment by stronges** [comment]
双备份升级是怎样的流程，可以提供相关资料么

**Comment by stronges** [comment]
AC6368A双备份升级，除去应用程序和备份程序， flash必须分配的空间有哪些，比如 vm最少分配多少？BTIF占用多少？ 还是没搞清楚vm BITF是干嘛的,！ 相关例程和资料可以提供？

**Comment by yzb201611** [comment]
一般j_isd.bin大小是实际烧写到flash，双备份结构vm大小是ini文件配置大小，btif也是ini配置大小。vm是为了存储程序中掉电保存信息，比如上次连接手机mac地址之类；btif是存储仅写一次的配置信息，如一些频偏校准值，MAC地址等。

**Comment by yzb201611** [comment]
> 
> 
> AC6368A双备份升级，除去应用程序和备份程序， flash必须分配的空间有哪些，比如 vm最少分配多少？BTIF占用多少？ 还是没搞清楚vm BITF是干嘛的,！ 相关例程和资料可以提供？

**Comment by stronges** [comment]
据你们所说，目前uart使用自定义协议升级只支持双备份升级, JL_RCSP APP OTA是单还是双备份升级？我可以实现用ble和uart两种升级方式一体么？
