### ISSUE TITLE
关于Mesh 烧写信息

### ISSUE THREAD

**Issue by Tsai1005** [Jieli-Tech/fw-AC63_BT_SDK#27]
为配合客户生产，现在需要整理Mesh 方案预烧录的信息项：
 - [ ] 三元组
 - [ ] App key
 - [ ] Net key

`Note 暂定烧写器与OTA 分别支持，如需要其他信息，请Comment 添加`

**Comment by jamin3702** [comment]
v0.9.2 已添加支持
