### ISSUE TITLE
关于bootloader

### ISSUE THREAD

**Issue by stronges** [Jieli-Tech/fw-AC63_BT_SDK#29]
我们想自己写boot,  可以实现么，如果可以实现，能不能提供下资料参考

**Comment by rixin-Tech** [comment]
不公开，你想实现什么功能？

**Comment by stronges** [comment]
按照自己的协议通过ble && uart给设备升级

**Comment by rixin-Tech** [comment]
> 按照自己的协议通过ble && uar

**Comment by rixin-Tech** [comment]
> 按照自己的协议通过ble && uart给设备升级

按照现有的升级不能满足你的需求吗？

**Comment by stronges** [comment]
> > 按照自己的协议通过ble && uart给设备升级
> 
> 按照现有的升级不能满足你的需求吗？

需求写boot, 可以按照自己的方式升级，比如可以按照需求自由切换 boot程序-应用程序。 可以通过uart/ble方式接收升级包等

**Comment by stronges** [comment]
> 按照现有的升级不能满足你的需求吗？

需求写boot, 可以按照自己的方式升级，比如可以按照需求自由切换 boot程序-应用程序。 可以通过uart/ble方式接收升级包等

**Comment by Tsai1005** [comment]
后续支持二级bootloader 用户自定义升级协议
