### ISSUE TITLE
输出数据会被无规律打断

### ISSUE THREAD

**Issue by forrestan** [Jieli-Tech/fw-AC63_BT_SDK#31]
#define WS_OUT	IO_PORTA_08//IO_PORTB_08
void Ws_SendByte(u8 data)
{
	u8 i=8,j;
	for(i=0; i<8; i++)
	{
		if(data&0x80)  //send 1
		{
			gpio_write(WS_OUT, 1);
			delay(0);
			gpio_write(WS_OUT, 0);
			data<<=1; 		 //左移一位
		}
		else // send 0
		{
			gpio_write(WS_OUT, 1);
			data<<=1; 	//左移一位
			gpio_write(WS_OUT, 0);
			delay(0);
		}
	}
}
void Ws_play()
{
  int i;
	
	for(i=0;i<6;i++)
	{
		Ws_SendByte(RainBow[i]);
		Ws_SendByte(RainBow[i]);
		Ws_SendByte(RainBow[i]);
	}

}
正确波形

![QQ截图20201209094718](https://user-images.githubusercontent.com/75365364/101563159-b91e0f80-3a03-11eb-9c60-4082c30d6ad7.png)

错误波形：

![1](https://user-images.githubusercontent.com/75365364/101563323-07cba980-3a04-11eb-983d-794907c4d0d2.png)
![21](https://user-images.githubusercontent.com/75365364/101563339-0d28f400-3a04-11eb-9a81-a843770f0b2c.png)
![041](https://user-images.githubusercontent.com/75365364/101563352-12863e80-3a04-11eb-8545-2376150e4a2b.png)

**Comment by rixin-Tech** [comment]
关闭中断

**Comment by forrestan** [comment]
关闭哪个中断？

**Comment by rixin-Tech** [comment]
local_irq_disable();
//TODO：

local_irq_enable();

**Comment by forrestan** [comment]
看到了，谢谢。

**Comment by rixin-Tech** [comment]
对时间敏感，切消耗时间比较久的波形可以使用spi do 来dma输出
