### ISSUE TITLE
关于flash分布

### ISSUE THREAD

**Issue by stronges** [Jieli-Tech/fw-AC63_BT_SDK#33]
可以给个内存布局图么？ 
![image](https://user-images.githubusercontent.com/33445686/102326753-c4eb7200-3fbf-11eb-8614-e752d3c50ddd.png)

![image](https://user-images.githubusercontent.com/33445686/102326781-cd43ad00-3fbf-11eb-8a32-f58e8cb3c04d.png)
这是有没有开ble ota对比，只能看到vm和flash减少， 入口地址是0x1E00120， 那么从上图来看，FLASH_BIN_SIZE的起始地址应该是0,  根据你们所说，boot的起始地址为1e000100， 那么boot有多大了？

**Comment by rixin-Tech** [comment]
1e000100 是逻辑地址，你对比一下芯片的memory 介绍

**Comment by stronges** [comment]
> 1e000100 是逻辑地址，你对比一下芯片的memory 介绍

ac6368A, 哪里有memery介绍，datasheet上没有

**Comment by rixin-Tech** [comment]
![image](https://user-images.githubusercontent.com/20225862/102434749-57d3ed00-4050-11eb-9769-21bf3f9b9be8.png)

**Comment by xjtuecho** [comment]
ac6368a是否有详细一些的用户手册？datasheet太简略信息太少了。

**Comment by Tsai1005** [comment]
@xjtuecho 用户手册不支持线上发布，请联系代理商和FAE

**Comment by xjtuecho** [comment]
> @xjtuecho 用户手册不支持线上发布，请联系代理商和FAE

代理商说没有datasheet，就是这个仓库里面的那个9页的pdf

**Comment by rixin-Tech** [comment]
![image](https://user-images.githubusercontent.com/20225862/144773142-76cb4b08-e35d-422e-aeb6-74d4b4abca2e.png)
