### ISSUE TITLE
关于ble和uart双备份升级

### ISSUE THREAD

**Issue by stronges** [Jieli-Tech/fw-AC63_BT_SDK#36]
要实现ble和uart双备份升级方式并存，需要配置和实现什么东西，目前只能从官方了解到一些模糊的说法，并没有具体的文档指导，如果涉及到一些接口的实现，例如之前给出的rcsp_ch_loader_download.c，官方历程里没有直观的注释，不容易理解。

**Comment by yzb201611** [comment]
双备份升级可以参考include_lib/update/dual_bank_updata_api.h的api来实现，接口都有详细的注释。
