### ISSUE TITLE
关于usr_timeout_add()

### ISSUE THREAD

**Issue by tylerYu123** [Jieli-Tech/fw-AC63_BT_SDK#38]
我们调用usr_timeout_add （）的实例如下： 
     timerSeq = usr_timeout_add(NULL  , LsUartDev_CbFuncOfUsrTimer , 20 , 0 ) ;

 请问超时调用回调函数后， 该定时器是否会被系统自动删除 ？

**Comment by rixin-Tech** [comment]
会
