### ISSUE TITLE
AC6366C的串口

### ISSUE THREAD

**Issue by forrestan** [Jieli-Tech/fw-AC63_BT_SDK#40]
在使用AC6366C的串口UART1RXC时，无法收到信息，而且发外设的TX也被拉低了。
但是我用AC6311A，相同的程序就正常，只是接口定义不同，其他程序都相同。
AC6366C的接口定义：
#define UART_TX	IO_PORTA_00
#define UART_RX	IO_PORTA_01
AC6311A的接口定义：
#define UART_TX	IO_PORTA_05
#define UART_RX	IO_PORTA_06

是不是把IO_PORTA_01的串口接收功能关闭了？

**Comment by rixin-Tech** [comment]
IO_PORTA_01 是mic脚

**Comment by forrestan** [comment]
不能再做串口的RX脚用了，是吧？

**Comment by forrestan** [comment]
> IO_PORTA_01 是mic脚

不能再做串口的RX脚用了，是吧？

**Comment by rixin-Tech** [comment]
你看看mic的配置，没被占用的情况是可以做串口的

**Comment by forrestan** [comment]
> 你看看mic的配置，没被占用的情况是可以做串口的

看软件并没有占用。但幅值被拉的很低。
