### ISSUE TITLE
PC4口电平异常

### ISSUE THREAD

**Issue by REYNJHR** [Jieli-Tech/fw-AC63_BT_SDK#45]
芯片6965，上电后PC4一直默认输出高？即使在int main（）中立即拉低PC4还是会有15ms的高电平，如何解决？
int main()
{

    gpio_set_pull_up(IO_PORTC_04,0);
    gpio_set_pull_down(IO_PORTC_04,0);
    gpio_set_direction(IO_PORTC_04,0);
    gpio_set_output_value(IO_PORTC_04,0);
    。
    。

**Comment by rixin-Tech** [comment]
那个版本的sdk出现这个。

**Comment by REYNJHR** [comment]
1.2和1.0都是

**Comment by rixin-Tech** [comment]
pc4 在启动阶段会打开上拉。此操作在mask里面，无法修改。
