### ISSUE TITLE
使能音量同步后，通过按键将音量减到没有声音后，继续按音量减，此时再按音量加后发现音量就再也加不上去了。只有切换模式或者重启音量才能恢复正常。什么原因？如何解决？

### ISSUE THREAD

**Issue by REYNJHR** [Jieli-Tech/fw-AC63_BT_SDK#53]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by REYNJHR** [comment]
696x  1.2sdk

**Comment by Tsai1005** [comment]
音频系列SDK 请联系代理商或FAE 线下支持
