### ISSUE TITLE
用户非正确升级,导致变砖,蓝牙信号显示JL_AI_UBOOT,这个问题还能通过手机APP解决吗

### ISSUE THREAD

**Issue by cesar0** [Jieli-Tech/fw-AC63_BT_SDK#54]
客户在升级过程中突然断电

**Comment by yzb201611** [comment]
使用哪个sdk的版本测试，部分版本的升级loader采用默认蓝牙名配置，最新080版本使用sdk同蓝牙名配置，试试更新tools目录下ota.bin生成新的升级问题试试。
