### ISSUE TITLE
nRF Mesh unable to Connect node after provisioned

### ISSUE THREAD

**Issue by mikewen** [Jieli-Tech/fw-AC63_BT_SDK#55]
用 'nRF Mesh' Android App 'Add node' ( SIG Generic_On_Off_Server ) 后, 无法再次连接.  SDK 0.7.0 and 0.8.0 都试过了. 
如果用 bt_mesh_reset 强制 reset, 再用 'nRF Mesh' delete node, 可以重新 'Add Node'.
是不是和定期广播有关?

**Describe the bug**
After using 'nRF Mesh' Android App to 'Add Node', unable to connect after disconnect the node.

**To Reproduce**
1. Use 'nRF Mesh' to 'Add Node', bind key.
2. Disconnect or exit the 'nRF Mesh' App
3. Click 'connect'
4. Scanner keep looking but unable to find the provisioned nodes

**Expected behavior**
'nRF Mesh' App should be able to find provisioned nodes

**Smartphone (please complete the following information):**
 - Device: LG G7
 - OS: Android
 - SDK Version, tried both 0.7.0 and 0.8.0

**Comment by hhy-ccj** [comment]
是哪个系列的芯片，nRF Mesh是哪个版本

**Comment by NoCodeNoLife-404** [comment]
![image](https://user-images.githubusercontent.com/56384032/110267190-3ef92900-7ffa-11eb-80a5-4bbf35bf71e7.png)
将lib_btctrler_config.c文件中的ble_disable_wait_enable改为0

**Comment by mikewen** [comment]
AC6369F,  'nRF Mesh' 是 3.1.0 
试了 ble_disable_wait_enable = 0，还是不行

**Comment by NoCodeNoLife-404** [comment]
是否有尝试清空flash和rebuild代码？

**Comment by mikewen** [comment]
rebuild代码 试过了, 不行.  怎样清空flash?

**Comment by NoCodeNoLife-404** [comment]
https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/releases/download/v2.4.1/nRF.Mesh.-.V.-.2.4.1.apk
请使用这个版本的nRF Mesh测试下

**Comment by mikewen** [comment]
这个版本的nRF Mesh测试可以了!  多谢!

**Comment by hhy-ccj** [comment]
> 这个版本的nRF Mesh测试可以了! 多谢!

对于新版本软件不适配的问题，我们后续会跟进。

**Comment by hhy-ccj** [comment]
nRF Mesh 新版本 3.1.0不适配，稍后解决
