### ISSUE TITLE
MESH 可以用 CODED PHY 吗?

### ISSUE THREAD

**Issue by mikewen** [Jieli-Tech/fw-AC63_BT_SDK#56]
现在的 SDK 支持 coded phy 吗?

代码里: set_connection_data_phy  注释掉了,  去掉就可以吗?

MESH 可以用 CODED PHY 吗?

**Comment by hhy-ccj** [comment]
> 现在的 SDK 支持 coded phy 吗?
> 
> 代码里: set_connection_data_phy 注释掉了, 去掉就可以吗?
> 
> MESH 可以用 CODED PHY 吗?

现在mesh非连接通信暂不支持coded phy，非连接下只有Core 5.0 的 extended adv 格式包才支持 coded / 2M PHY；“set_connection_data_phy ” 是针对连接状态下的PHY切换。

**Comment by mikewen** [comment]
那连接通信可以?  有没有例子?  谢谢!

**Comment by hhy-ccj** [comment]
> 那连接通信可以? 有没有例子? 谢谢!

连接通信下，**config_btctler_le_features** 或上 **LE_CODED_PHY** 即可，前提是手机或者其它主机设备支持这个特征。 
example:
`const uint64_t config_btctler_le_features = LE_ENCRYPTION | LE_CODED_PHY;`

**Comment by hhy-ccj** [comment]
mesh adv coded 特性稍后添加。

**Comment by hhy-ccj** [comment]
mesh adv coded 特性稍后添加。
