### ISSUE TITLE
用 AC63_BT_SDK 开发 AC6969A

### ISSUE THREAD

**Issue by mikewen** [Jieli-Tech/fw-AC63_BT_SDK#57]
'关于AC63xx 命名规则' 提到 AC636X 和 AC696X 系列 只是 Flash 电压不同.

那可以用 AC63_BT_SDK 开发 AC696X 系列吗? ( AC6965A, AC6969A, etc )

有什么注意事项? ( 比如电压检测是不是要该. )

**Comment by Tsai1005** [comment]
可以的，Project 介绍已更新说明
