### ISSUE TITLE
6368a 只开了ble 从机at模式， 关了edr ，广播间隔设置成1s ，信道开了37 ，发射功率（0~9）设置成2，在蓝牙只广播状态下，任然还是有4ma的功耗，请教一下4ma是否是正常的？若还要降功耗还能做什么？at模式下这颗料能做到多低的功耗？

### ISSUE THREAD

**Issue by REYNJHR** [Jieli-Tech/fw-AC63_BT_SDK#58]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by REYNJHR** [comment]
0.7版本SDK

**Comment by hhy-ccj** [comment]
> 0.7版本SDK

有进入低功耗模式吗(< >打印)，没用到的 IO 进入睡眠前有关掉吗？

**Comment by hhy-ccj** [comment]
长时间没有得到回复，关闭问题
