### ISSUE TITLE
[mesh] VM 读写 要注意什么?

### ISSUE THREAD

**Issue by mikewen** [Jieli-Tech/fw-AC63_BT_SDK#60]
如果想用 VM 保存一些 data, 是不是加１个到　INFO_SETTING_INDEX　就可以 用　vm_read/ vm_write 了?
一个 index 可以保存多少 data ?

**Comment by hhy-ccj** [comment]
> 如果想用 VM 保存一些 data, 是不是加１个到　INFO_SETTING_INDEX　就可以 用　vm_read/ vm_write 了?
> 一个 index 可以保存多少 data ?

可以直接使用 `model_api.c` 里面的 `info_store` 和 `info_load` 接口来记忆数据，只要在 `MAC_ADDR_INDEX` 往下添加 index 就可以，一个索引最大支持 **0xFFF** 个bytes。
