### ISSUE TITLE
AC6351D  USB休眠唤醒功能在“AC630N_bt_data_transfer_sdk_release_v0.8.0”版本上无法实现

### ISSUE THREAD

**Issue by pepsi1021** [Jieli-Tech/fw-AC63_BT_SDK#65]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rixin-Tech** [comment]
[usb_suspend.zip](https://github.com/Jieli-Tech/fw-AC63_BT_SDK/files/6241567/usb_suspend.zip)

1、include_lib/driver/device/usb/device/usb_stack.h
`#define     USB_SUSPEND_RESUME      1`

2、对应的board.c里面
```
/************************** otg data****************************/
#if TCFG_OTG_MODE
struct otg_dev_data otg_data = {
    .usb_dev_en = 0,
    .slave_online_cnt = TCFG_OTG_SLAVE_ONLINE_CNT,
    .slave_offline_cnt = TCFG_OTG_SLAVE_OFFLINE_CNT,
    .host_online_cnt = TCFG_OTG_HOST_ONLINE_CNT,
    .host_offline_cnt = TCFG_OTG_HOST_OFFLINE_CNT,
    .detect_mode = TCFG_OTG_MODE,
    .detect_time_interval = TCFG_OTG_DET_INTERVAL,
};


#endif
REGISTER_DEVICES(device_table) = {
    { "otg",     &usb_dev_ops, (void *) &otg_data},
};
```
![image](https://user-images.githubusercontent.com/20225862/113254694-802ee100-92f9-11eb-9dad-e0363c0977e9.png)
![image](https://user-images.githubusercontent.com/20225862/113254715-845afe80-92f9-11eb-89b0-a63427bdbfa2.png)

**Comment by rixin-Tech** [comment]
[696_cpu.zip](https://github.com/Jieli-Tech/fw-AC63_BT_SDK/files/6261535/696_cpu.zip)

**Comment by rixin-Tech** [comment]
对部分场景不需要系统进入低功耗模式，没配置唤醒io为dp的用户，在mac电脑上需要打开sof中断

1、注释sof中断
    
![image](https://user-images.githubusercontent.com/20225862/124212652-ed812680-db21-11eb-9fb8-d4c2637019a4.png)
2、收到休眠消息，使能sof中断
![image](https://user-images.githubusercontent.com/20225862/124212724-0b4e8b80-db22-11eb-85a9-cfb28d7ad1aa.png)
3、成功休眠后sof中断就会停止进入，唤醒成功后，sof中断会再次进入
![image](https://user-images.githubusercontent.com/20225862/124212810-2e793b00-db22-11eb-89ba-26b85961c800.png)

**Comment by rixin-Tech** [comment]
假休眠不需要打开USB_ROOT2 USB_SUSPEND_RESUME
1、把sConfigDescriptor描述符的power属性 0x80-->0xA0
![image](https://user-images.githubusercontent.com/20225862/143681956-f0824fac-789c-479e-80c2-791bc6f7cf7a.png)

2、usb_isr里面最前面标记退出休眠
3、打开suspend中断
4、在suspend中断里面记录已经进入休眠

![image](https://user-images.githubusercontent.com/20225862/143681979-8bf2db77-f3cd-497c-8785-8ebc43924982.png)


5、在需要唤醒的地方调用一下 usb_remote_wakeup
