### ISSUE TITLE
PWM 支持 High Drive 吗?

### ISSUE THREAD

**Issue by mikewen** [Jieli-Tech/fw-AC63_BT_SDK#71]
普通的 GPIO 可以用 gpio_set_hd 

PWM 支持 High Drive 吗?
如果支持，怎么用呢?

**Comment by wjjjb123** [comment]
led_pwm可以设置强弱驱，如果芯片没有led_pwm 或者 用的是其他pwm，如timer_pwm，mc_pwm，那么设置强弱驱可以试试gpio_set_hd，gpio_set_hd0
