### ISSUE TITLE
蓝牙 开启OTA 功能后  蓝牙名字 最多变成了16BYTE  我想显示 20BYTE 怎么处理

### ISSUE THREAD

**Issue by shifa2008** [Jieli-Tech/fw-AC63_BT_SDK#73]
蓝牙 开启OTA 功能后  蓝牙名字 最多变成了16BYTE  我想显示 20BYTE 怎么处理

**Comment by jamin3702** [comment]
协议规定 adv包和rsp包各自最多负载只有31bytes，所以只能根据自己需求整合数据，取舍；腾出空间放更长的蓝牙名字
