### ISSUE TITLE
AC632系列RTC驱动用不了

### ISSUE THREAD

**Issue by pepsi1021** [Jieli-Tech/fw-AC63_BT_SDK#74]
AC632系列RTC驱动用不了，另外挂32.768khz晶振有参考原理图吗

**Comment by chengzeqiang** [comment]
1、[cpu.zip](https://github.com/Jieli-Tech/fw-AC63_BT_SDK/files/6375781/cpu.zip)
更改为文件名为cpu.a并替换旧cpu.a

2、[rtc.h.txt](https://github.com/Jieli-Tech/fw-AC63_BT_SDK/files/6375799/rtc.h.txt)
更改文件名为rtc.h并替换旧rtc.h

3、![image](https://user-images.githubusercontent.com/83212621/116059399-60e66200-a6b3-11eb-9af7-be77d92393a6.png)
在user_cfg_id.h添加
#define     VM_ALARM_0                     44
#define     VM_ALARM_1                     45
#define     VM_ALARM_2                     46
#define     VM_ALARM_3                     47
#define     VM_ALARM_4                     48
#define     VM_ALARM_MASK                  49
#define     VM_ALARM_NAME_0                50
#define     VM_ALARM_NAME_1                51
#define     VM_ALARM_NAME_2                52
#define     VM_ALARM_NAME_3                53
#define     VM_ALARM_NAME_4                54

4、![image](https://user-images.githubusercontent.com/83212621/116059559-8c694c80-a6b3-11eb-8f97-4d7804409d6e.png)
在include_lib/drive/cpu/bd19/asm/includes.h 添加 #include "asm/rtc.h"
