### ISSUE TITLE
AC6368A的PA6不用的话应该如何处理？

### ISSUE THREAD

**Issue by xjtuecho** [Jieli-Tech/fw-AC63_BT_SDK#76]
目前我的应用中，7脚和8脚作为串口UART1使用，没有使用USB和PA6，芯片的PA6实际上也在8脚，没有专门处理。
连接USBTTL模块（CH340方案）工作正常，但是去掉7脚和8脚上的TX和RX两条线，只用VCC和GND为模块供电，上电后软件无法运行，可能是什么原因呢？
这个芯片PB1和PA6都是绑定了UART0的RX，为什么不绑定一个TX呢？可以做LOG输出使用。
另外AC6368A是否有比较详细的芯片用户手册？datasheet本身太简略了。

**Comment by rixin-Tech** [comment]
串口可以使用任意io做接收发送，pb1有长按复位功能，如不需要就在ini文件，或者烧写器的选项里面关闭长按复位功能。
