### ISSUE TITLE
Readme 中提到的 OTA 开发说明 缺失

### ISSUE THREAD

**Issue by Davi-He** [Jieli-Tech/fw-AC63_BT_SDK#79]
fw-AC63_BT_SDK/apps/hid/ 下的readme 提到：
2.1 安卓端开发说明：详见tools目录下Android_杰理OTA外接库开发说明
2.2 IOS端开发说明： 详见tools目录下IOS_杰理OTA外接库开发说明

但是没找到tools 下有这个 文件

**Comment by main010** [comment]
已经修改readme, APP相关开发资料有对应的git仓库

**Comment by main010** [comment]
安卓：https://github.com/Jieli-Tech/Android-JL_OTA
IOS： https://github.com/Jieli-Tech/iOS-JL_OTA
