### ISSUE TITLE
AC630N_bt_data_transfer_sdk_release_v0.9.1数据SDK  传统蓝牙HID增加电量显示功能

### ISSUE THREAD

**Issue by pepsi1021** [Jieli-Tech/fw-AC63_BT_SDK#80]
目前有较多客户提出这个需求，传统蓝牙耳机及BLE HOGP都支持电量显示，如果传统蓝牙HID能加入这个功能，将极大提升终端客户产品竞争力。

**Comment by jamin3702** [comment]
v0.9.2版本hid case 已调加支持，打开宏配置就可以，app_keyboard.c 实现示例代码：

#if (TCFG_USER_EDR_ENABLE && TCFG_SYS_LVD_EN && USER_SUPPORT_PROFILE_HFP)
    //edr通过hfp显示电量
    __set_disable_sco_flag(1);
    __bt_set_update_battery_time(60);
    get_battery_value_register(bt_get_battery_value);   /*电量显示获取电量的接口*/
#else
    __bt_set_update_battery_time(0);
#endif
