### ISSUE TITLE
AC695X MCPWM当做普通timer用

### ISSUE THREAD

**Issue by pepsi1021** [Jieli-Tech/fw-AC63_BT_SDK#90]
AC695X MCPWM当做普通timer用，有没有对应API或者demo？

**Comment by wjjjb123** [comment]
/******************************* 以下是查询法的参考代码，以mctmr7为例*********************/
//简单的delay函数，如果想用mctmr4，则将代码中的数组 7 修改成 4
void mctimer_udelay(u32 us)
{
    JL_MCPWM->MCPWM_CON0 &= ~BIT(8 + 7);
    JL_MCPWM->TMR7_CNT = 0;
    JL_MCPWM->TMR7_PR = clk_get("mcpwm") / 1000000 * us;
    JL_MCPWM->TMR7_CON = BIT(10) | BIT(0);
    JL_MCPWM->MCPWM_CON0 |= BIT(8 + 7);
    while(!(JL_MCPWM->TMR7_CON & BIT(12)));
    JL_MCPWM->TMR7_CON = BIT(10);
    JL_MCPWM->MCPWM_CON0 &= ~BIT(8 + 7);
}

/******************************* 以下是中断法的参考代码 *********************/
struct mctmr_t {
	u32 mctmr_con;
	u32 mctmr_cnt;
	u32 mctmr_prd;
};
/*
 * @brief  mctmr0~7 共一个中断函数
*/
___interrupt
void mctmr_isr(void)
{
	struct mctmr_t *mctmr = NULL;
	for (u8 num = 0; num < 8; num ++) {
		mctmr = ((struct mctmr_t *)&JL_MCPWM->TMR0_CON) + num * sizeof(struct mctmr_t);
		if ((mctmr->con & BIT(8)) && (mctmr->con & BIT(12))) {	//起pnding
			mctmr->con |= BIT(10);								//clr pnding
			/***************
				to  do
			****************/
		}
	}
}
/*
 * @arg mctmr_num : mctmr号，范围0~7
*/ 
void mctimer_init(u8 mctmr_num)
{
	struct mctmr_t *mctmr = ((struct mctmr_t *)&JL_MCPWM->TMR0_CON) + mctmr_num * sizeof(struct mctmr_t);
	JL_MCPWM->MCPWM_CON0 &= ~BIT(8 + mctmr_num);		//关闭时钟源
	mctmr->con = 0;
	mctmr->cnt = 0;
	mctmr->prd = 100 * (clk_get("mcpwm") / 2 / 1000));	//100ms
	mctmr->con |= (0b0001 << 3);						//时钟源2分频
	mctmr->con |= BIT(8);								//使能中断
	request_irq(41, 5, mctmr_isr, 0);					//注册中断函数
	mctmr->con |= BIT(10) | BIT(0);						//mctimer模块使能
	JL_MCPWM->MCPWM_CON0 |= BIT(8 + mctmr_num);			//打开时钟源
}
