### ISSUE TITLE
SPP发送完成回调是否有进一步说明？

### ISSUE THREAD

**Issue by xjtuecho** [Jieli-Tech/fw-AC63_BT_SDK#91]
SPP初始化时注册了3个回调函数，前两个都比较好理解，第三个at_spp_send_wakeup是否有进一步说明或者例子？
比如UART接口收到的数据需要通过SPP转发出去，应该如何实现比较好？
```
	spp_api->regist_recieve_cbk(0, at_spp_recieve_cbk);
	spp_api->regist_state_cbk(0, at_spp_state_cbk);
	spp_api->regist_wakeup_send(NULL, at_spp_send_wakeup);
```

**Comment by xjtuecho** [comment]
```
spp_api->send_data(NULL, data, len)
```
还有SPP发送的函数，返回值的意义是什么？
对输入的数据长度len有没有什么限制？
send_data只是写入协议栈buffer就返回还是阻塞至发送完成（同步？异步？）？
如何判断发送是否成功？
SPP协议栈内部buffer多大？len超过buffer大小以后会是什么行为？

**Comment by xjtuecho** [comment]
实测SPP内部buffer是660字节，超过以后直接返回2，返回0表示发送成功。
感觉send_data是同步发送的，函数返回以后busy_state返回0表示不是忙状态。

**Comment by jamin3702** [comment]
send data 是异步发数，需要等协议栈发送成功回调事件at_spp_send_wakeup才能释放发送buff
