### ISSUE TITLE
AC6369C 是否支持PAP 功能？

### ISSUE THREAD

**Issue by lewisxhe** [Jieli-Tech/fw-AC63_BT_SDK#92]
AC6369C 是否支持PAP 功能？ 是否有相关示例 ？

**Comment by jamin3702** [comment]
AC636N 系列固定io是 tx-pc1，rx-pc2；要确保芯片又对应的io；然后蓝牙初始化前调如下接口打开就可以
void bt_set_rxtx_status_enable(u8 en);
