### ISSUE TITLE
6366N的Mic启动录音并且压缩后，不再响应按键处理，系统会reset

### ISSUE THREAD

**Issue by zhouzm2010gmail** [Jieli-Tech/fw-AC63_BT_SDK#95]
bug描述
6366N的Mic启动录音并且压缩后，串口会一直打印adc以及encode的回调函数被调用，但是不再响应按键处理，无法停止，系统会reset。

复现过程：
在某个按键按下时，调用下面的代码：
	printf(">>>audio_start\n");
	app_hid_env.audio_start = 1;
    extern int audio_adc_open_demo(void);
    audio_adc_open_demo();
	extern int audio_mic_enc_open(int (*mic_output)(void *priv, void *buf, int len), u32 code_type);
	//audio_mic_enc_open(mic_output, AUDIO_CODING_OPUS);//opus encode test */
	audio_mic_enc_open(mic_output, AUDIO_CODING_OPUS);//opus encode test */
	printf(">>>audio_start OK\n");
  

期待行为：
启动录音和压缩后，中途可以通过按键停止录音。

使用的V0.7_6366C的SDK，参考的keyboard的工程

**Comment by jamin3702** [comment]
录音编码会占用cpu，试试提高时钟频率
