### ISSUE TITLE
蓝牙音频传输问题

### ISSUE THREAD

**Issue by songyun-summer** [Jieli-Tech/fw-AC63_BT_SDK#97]
请问 把外界音频信号通过DAC直接连到蓝牙的MIC 上，然后再通过蓝牙，把收到的信号发射出去，音量大小通过串口控制，
芯片用的是6965E，能否做到？

**Comment by jamin3702** [comment]
不是AC63 SDK 支持的功能范围

**Comment by robot-bear** [comment]
696的sdk有这个功能的
