### ISSUE TITLE
请问632N怎么添加描述符（Characteristic User Description）

### ISSUE THREAD

**Issue by Jim256256** [Jieli-Tech/fw-AC63_BT_SDK#98]
Dear JL 工程师：
目前我们在开发632N芯片，遇到个问题请帮忙解答一下，谢谢。

SDK和工具版本：
SDK : 092
make gatt tool : make_gatt_services_v1.0.4

需求：
添加用户描述符（Characteristic User Description），如下图：
![image](https://user-images.githubusercontent.com/76936426/126141459-ea1bded9-caaa-4235-b164-bcad0608ee5c.png)

请指导一下在改平台如何添加，谢谢。

**Comment by jamin3702** [comment]
试使用关键字 CHARACTERISTIC_USER_DESCRIPTION 添加
    CHARACTERISTIC_USER_DESCRIPTION,READ | DYNAMIC ,

**Comment by Jim256256** [comment]
收到，多谢！
