### ISSUE TITLE
AC692x系列关于苹果手机MTU问题

### ISSUE THREAD

**Issue by lxcxzlm** [Jieli-Tech/fw-AC63_BT_SDK#99]
你好！

       我在使用AC6926芯片BLE功能与苹果手机连接时，苹果手机声明MTU为185个字节。而同一个手机同一个APP在与Cypress 20706芯片连接时则声明MTU为527个字节。
       开始我认为这是APP设置的，叫APP开发人员去修改，然后APP开发人员告诉我苹果手机不能设置。都是系统默认的。

       我想请问一下，这两个芯片为什么会有这样的差别。客户想一包数据传输280个字节。这个在AC692的平台上能实现么?我使用的SDK为AC692x_SDK_release_V2.6.3 。
![3C`9A$%8ZO7{Q%4NO`0J6P5](https://user-images.githubusercontent.com/51643584/126420861-70211491-dae7-484e-8ef7-52c95de2c547.jpg)
![4U4XB1_EB0@3%W79TC M@77](https://user-images.githubusercontent.com/51643584/126420877-66266848-a117-4d96-9ded-118ac20614e3.jpg)

**Comment by jamin3702** [comment]
可以尝试添加支持DLE feature，使ios发送较大的mtu，在lib_btctrler_config.c配置示例如下：
const uint64_t config_btctler_le_features = LE_ENCRYPTION | LL_FEAT_DATA_LEN_EXT;

**Comment by jamin3702** [comment]
目前AC63 SDK 支持改feature

**Comment by lxcxzlm** [comment]
692系列的没有办法了么？

**Comment by lxcxzlm** [comment]
> 目前AC63 SDK支持改功能

请问692系列是否有办法能修改？ 我用的是AC692x_SDK_release_V2.6.3

**Comment by jamin3702** [comment]
找代理支持一下
